set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN B9 [get_ports d_in]
set_property PACKAGE_PIN H5 [get_ports d_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports d_in]
set_property IOSTANDARD LVCMOS33 [get_ports d_out]
set_property SLEW FAST [get_ports d_out]
set_property DRIVE 12 [get_ports d_out]
create_clock -period 40.000 -name clk -waveform {0.000 20.000} [get_ports clk]
